version: '3'

services:
  # Node js scraper for fetching data from mintos.com site
  scraper:
    image: kanocomputing/puppeteer:latest
    restart: always
    stdin_open: true
    tty: true
    volumes:
      - ./src/scraper:/var/www/html
      - ./config/scraper/start.sh:/start.sh
    working_dir: /var/www/html
    env_file:
      - .env
    entrypoint: ['sh', '/start.sh']
    user: root
    networks:
      - default

  # Laravel app services
  nginx:
    image: nginx
    restart: always
    depends_on:
      - php
    volumes:
      - ./src/api:/var/www/html
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.port=80"
      - "traefik.frontend.rule=Host:${APP_HOST}"
    networks:
      - default
      - traefik

  php:
    build:
      context: ./config/php
      dockerfile: Dockerfile
    depends_on:
      - mysql
      - redis
    working_dir: /var/www/html
    env_file:
      - .env
    restart: always
    volumes:
      - ./config/php/php.ini:/usr/local/etc/php/php.ini
      - ./config/php/start.sh:/start.sh
      - ./src/api:/var/www/html
    entrypoint: ['bash', '/start.sh']
    networks:
      - default

  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    command:
      - "--default-authentication-plugin=mysql_native_password"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - default

  redis:
    image: redis:latest
    restart: always
    networks:
      - default

  # nginx to serve static pa files
  nginx-pwa:
    image: nginx
    restart: always
    volumes:
      - ./src/pwa:/var/www/html
      - ./config/nginx-pwa/default.conf:/etc/nginx/conf.d/default.conf
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.port=80"
      - "traefik.frontend.rule=Host:${PWA_HOST}"
    networks:
      - default
      - traefik

  pwa-builder:
    image: node
    volumes:
      - ./src/pwa:/var/www/html
      - ./config/node-pwa/start.sh:/start.sh
    env_file:
      - .env
    entrypoint:
      - sh
      - /start.sh
    user: node

volumes:
  mysql-data:

networks:
  default:
    external: false
    driver: bridge
  traefik:
    external: true
