version: '3'

services:
  # Node js scraper for fetching data from mintos.com site
  scraper:
    image: kanocomputing/puppeteer:latest
    restart: always
    stdin_open: true
    tty: true
    volumes:
      - ./src/scraper:/var/www/html
      - ./config/scraper/start.sh:/start.sh
    working_dir: /var/www/html
    env_file:
      - .env
    entrypoint: ['sh', '/start.sh']
    user: root

  # Laravel app services
  nginx:
    image: nginx
    restart: always
    depends_on:
      - php
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./src/api:/var/www/html
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
  php:
    build:
      context: ./config/php
      dockerfile: Dockerfile
    depends_on:
      - mysql
      - redis
    working_dir: /var/www/html
    env_file:
      - .env
    restart: always
    volumes:
      - ./config/php/php.ini:/usr/local/etc/php/php.ini
      - ./src/api:/var/www/html

  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    command:
      - "--default-authentication-plugin=mysql_native_password"
    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    image: redis:latest
    restart: always

volumes:
  mysql-data:
